### PR TITLE
CI: Add codesandbox CI

### PR DESCRIPTION
**Pull request by Evalir**
Adds a CI pipeline for `use-wallet` for having automated deployments with the latest changes on every PR.

### CODE REVIEW

**Comment by Evalir** [comment]
We should be able to! I'll push a quick change to see.

**Comment by Evalir** [comment]
Huh, codesandbox seems to be hanging up on build. What's up? 🤔

**Comment by Evalir** [comment]
I think we can merge this @bpierre ; codesandbox seems to be hanging up on build but this seems to be a problem with the CI itself, not the config file. What do you think?

**Comment by bpierre** [comment]
@Evalir Do you think it is the same issue than the one we had with aragonUI’s devbox?

**Comment by Evalir** [comment]
Hmm yeah, even though this doesn't seem to be caused by a large build... Codesandbox CI doesn't seem that stable on some repos at all.

**Comment by bpierre** [comment]
Should we close this for now and make it an issue? Merging it in the current state would probably prevent future PRs to pass the checks ☹️

**Comment by Evalir** [comment]
Yeah, sadly I think we for now should make it an issue. :(

**Pull request closed without merging**
