### PR TITLE
Add FTM network

### PR DESCRIPTION
**Pull request by lilesper**

### CODE REVIEW

**Review by WissenIstNacht — APPROVED** [review]

**Comment by WissenIstNacht** [comment]
Thank you very much!

And sorry for the long response time.

**Comment by WissenIstNacht** [comment]
Hey, you might want to resolve the conflicts on this PR. Also, could you please remove the changes to `package.json`?

**Comment by hiddendragonXVII** [comment]
Np will update this week!

**Comment by lilesper** [comment]
I updated to resolve the merge conflicts & change the full name to match what I normally see on metamask.
let me know if anything else needs to be changed on this branch! kind regards ~ , ~

**Review by sasanpc85 — APPROVED** [review]

**Pull request merged**
